services:
  - type: web
    name: todo-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/tO_dO_aPP
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 